{{ config(schema='demo') }}

SELECT cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CALL_CENTER_SK') as Numeric(38,0))
as CC_CALL_CENTER_SK,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CALL_CENTER_ID') as VARCHAR(16) )
as CC_CALL_CENTER_ID,
case when (JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_REC_START_DATE')) = '' then null
else  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_REC_START_DATE') as DATE) end
as CC_REC_START_DATE,
case when (JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_REC_END_DATE')) = '' then null
else  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_REC_END_DATE') as DATE) end
as CC_REC_END_DATE,
case when (JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CLOSED_DATE_SK')) = '' then null
else  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CLOSED_DATE_SK') as Numeric(38,0)) end
as CC_CLOSED_DATE_SK,
case when (JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_OPEN_DATE_SK')) = '' then null
else  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_OPEN_DATE_SK') as Numeric(38,0)) end
as CC_OPEN_DATE_SK,
case when (JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_NAME')) = '' then null
else  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_NAME') as VARCHAR(50)) end
as CC_NAME,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CLASS') as VARCHAR(50))
as CC_CLASS,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_EMPLOYEES') as  Numeric(38,0))
as CC_EMPLOYEES,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_SQ_FT') as  Numeric(38,0))
as CC_SQ_FT,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_HOURS') as VARCHAR(20))
as CC_HOURS,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_MANAGER') as VARCHAR(40))
as CC_MANAGER,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_MKT_ID') as Numeric(38,0))
as CC_MKT_ID,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_MKT_CLASS') as VARCHAR(50))
as CC_MKT_CLASS,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_MKT_DESC') as VARCHAR(100))
as CC_MKT_DESC,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_MARKET_MANAGER') as VARCHAR(40))
as CC_MARKET_MANAGER,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_DIVISION') as Numeric(38,0))
as CC_DIVISION,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_DIVISION_NAME') as VARCHAR(50))
as CC_DIVISION_NAME,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_COMPANY') as Numeric(38,0))
as CC_COMPANY,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_COMPANY_NAME') as VARCHAR(50))
as CC_COMPANY_NAME,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_STREET_NUMBER') as VARCHAR(10))
as CC_STREET_NUMBER,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_STREET_NAME') as VARCHAR(60))
as CC_STREET_NAME,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_STREET_TYPE') as VARCHAR(15))
as CC_STREET_TYPE,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_SUITE_NUMBER') as VARCHAR(10))
as CC_SUITE_NUMBER,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CITY') as VARCHAR(60))
as CC_CITY,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_COUNTY') as VARCHAR(30))
as CC_COUNTY,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_STATE') as VARCHAR(2))
as CC_STATE,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_ZIP') as VARCHAR(10))
as CC_ZIP,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_COUNTRY') as VARCHAR(20))
as CC_COUNTRY,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_GMT_OFFSET') as Numeric(5,2))
as CC_GMT_OFFSET,
cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_TAX_PERCENTAGE') as Numeric(5,2))
as CC_TAX_PERCENTAGE, 
_airbyte_ab_id,
    _airbyte_emitted_at,
    getdate() as _airbyte_normalized_at
FROM "dev"."demo"."_airbyte_raw_call_center"
ORDER BY  cast(JSON_EXTRACT_PATH_TEXT(JSON_SERIALIZE(_airbyte_data),'CC_CALL_CENTER_SK') as Numeric(38,0)) desc